name: pull_request_test

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  pull_request_test:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ github.head_ref  }}

      - name: set value
        run: echo "test_value=test_value" >> $GITHUB_OUTPUT
        id: test_value

      - name: test
        if: steps.test_value.outputs.test_value == 'test_value'
        run: echo ${{ steps.test_value.outputs.test_value  }}

